### ISSUE TITLE
Updates to site.

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/BridgesUNCC.github.io#21]
I have pushed the C++ version 2.4.0 to bridges site
I have updated the docs with teh current 2.4.0 versions for all 3 languages (older versions of the doxygen documentation are available in another page accessible from the main page)

To do:
Need to finalize the Java and Python versions and then push zip of the 2.4.0 to site. Needs to happen by mid week or so.

Will update the docs after that.

**Comment by esaule** [comment]
long done
