### ISSUE TITLE
Using dataset  examples.. on the site.

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/BridgesUNCC.github.io#22]
Erik brought this up. 

David, you had created code fragements for each dataset we have on BRIDGES. WE want to add that in a pull down menu with the other website data structure tutorials. These can be part of the  testing scenario and then copied onto our website, like the other examples. Can you collect these together into the bridges_testing folder - maybe we can use  subfolder within the  webtutorial_testing_forthe_web. or just add them there if there is no name clash. 

If you already have them for Java (I am talking about the data site program fragements), then we can do the C++ and Python from there.

**Comment by squeetus** [comment]
@krs-world, @esaule: I'm cleaning these up and will add them to the Bridges_Testing repo as soon as I know they're working. 

At the moment, the datasource code snippets do not produce visualizations, and instead pull a random entry from the data source and print it to the console. Would it be more helpful to add a basic vis (perhaps a single list node) like all the other tests? This is trivial to add, so just let me know.

**Comment by krs-world** [comment]
No, this is not necessary. We just want to illustrate in these examples 
how to access the data through the BRIDGES API which I think you already 
had.  We have all the other examples to show thevisualizations 
with/without external datasets. I would suggest copy these fragments to 
teh testing directory, into the Mastercopy folder; we can prefix them as 
datasetXXXX or something.  Erik can help us with the Makefile  
modifications, if any.

     - krs

**Comment by squeetus** [comment]
Great, thanks for the response. So far I've been naming them {dataset}_snippet.java but I can swap the naming convention if that's preferable.

**Comment by krs-world** [comment]
Should be fine, so long as they dont confuse another test in teh same 
directory.

     --- krs

**Comment by esaule** [comment]
done
