### ISSUE TITLE
update team members page

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/BridgesUNCC.github.io#23]
Look at @squeetus he looks like a baby !
http://bridgesuncc.github.io/bridges_team.html

**Comment by krs-world** [comment]
All -- send me a recent pictures of yourself and I will update our team page.

**Comment by esaule** [comment]
Fell free to use this one:

https://cci.uncc.edu/sites/cci.uncc.edu/files/styles/directory-list/public/fields/directory/field_directory_image/erik-picture-2015-10.jpg?itok=aNIhoX4q

-- 
Dr Erik Saule
Assistant Professor at University of North Carolina at Charlotte (UNCC)
tel: +1 (704) 687-8580
web: http://webpages.uncc.edu/~esaule/
== 
Perform academic literature search on http://theadvisor.osu.edu/
