### ISSUE TITLE
using tutorial code in getting started?

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/BridgesUNCC.github.io#31]
Looking at the getting started, I am wondering whether we should use a tutorial code in the getting started page. Look at these 2 pages for instance:

http://bridgesuncc.github.io/bridges_setup_python_pycharm.html

http://bridgesuncc.github.io/bridges_setup_java_bluej.html

They don't use the same code and one is just the screen shot of a code. Probably we are not testing it. But using a tutorial exemple, we would know that it is an exemple that actually runs

Opinion?

**Comment by krs-world** [comment]
Completed -- except Netbeans and jGrasp.. if someone asks for it, we will do -- had difficulty in building these.
