### ISSUE TITLE
LineChart no visualization on live

### ISSUE THREAD

**Issue by LightBoat9** [BridgesUNCC/BridgesUNCC.github.io#34]
Complexity (Assignment 28) run on live:
http://bridges-cs.herokuapp.com/assignments/60/lsloop4

On clone:
http://bridges-clone.herokuapp.com/assignments/60/lsloop4

The JSON is the same. The same result happens from python and java. c++ is untested.

**Comment by esaule** [comment]
It seems we had not updated live. I thought we had. I redeployed live from upstream tested that line chart works.
