### ISSUE TITLE
Python code is broken in getting started

### ISSUE THREAD

**Issue by acbart** [BridgesUNCC/BridgesUNCC.github.io#47]
In particular, the `SLelement` function expects keyword arguments, not position arguments. Might be other issues.

**Comment by AlecGoncharow** [comment]
Oh wow, thanks for pointing that out, there are many thing wrongs with that python code snippet. Thanks for pointing that out. Will work on a fix.

**Comment by AlecGoncharow** [comment]
For the immediate case, you can refer to http://bridgesuncc.github.io/tutorials/SinglyLinkedList.html and go to the python tab for example starter code

**Comment by esaule** [comment]
So really the getting started should not have code in there. We should point to a tutorial page because these are automatically tested.

**Comment by esaule** [comment]
done
