### ISSUE TITLE
tutorial pages broken in https

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/BridgesUNCC.github.io#48]
reported by Toby Dragon.

if you load a tutorial page in https then the codes don't get imported and the iframe don't load.
example: https://bridgesuncc.github.io/tutorials/Array.html

someone knows how to fix that?

**Comment by krs-world** [comment]
We have always had this issue when you switch to https.. as I recall.  never really followed up to look at this more carefully.
	
	-krs

**Comment by esaule** [comment]
In the iframes, if we put https in the url, it seems to work, I am experimenting on this.

It also seems that the w3-include-html is pretty simple and may not work correctly with the http/https boundary. I am looking into it.

**Comment by esaule** [comment]
fixed
