### ISSUE TITLE
Python getting started pages are completely misleading

### ISSUE THREAD

**Issue by AlecGoncharow** [BridgesUNCC/BridgesUNCC.github.io#50]
Toby in discord was running into issues with getting python working in his local on windows. I remember it came up that a while back that these tutorials need to be reworked, and that did not happen so I am wondering if it may be worth just removing those pages at this point and redirecting them to links to the readme of this repo and the tutorials.

List of issues
* Links are pointing to outdated zip files
* Code in screenshots are no longer correct
* Makes the process seem more involved than it actually is / cross cutting in concerns.

**Comment by krs-world** [comment]
Pycharm pages have been updated.
