### ISSUE TITLE
Documentation Links Go To Older Versions

### ISSUE THREAD

**Issue by prestoncarman** [BridgesUNCC/BridgesUNCC.github.io#58]
The downloads tab on <https://bridgesuncc.github.io/index.html> shows a link to version 3.3.0. Some documentation links go to different versions:

* C++ is 3.2.2 <https://bridgesuncc.github.io/doc/cxx-api/current/html/index.html>
* Java is 3.2.2-21-gaad2999 <https://bridgesuncc.github.io/doc/java-api/current/html/index.html>
* Python is 3.3.0 <https://bridgesuncc.github.io/doc/python-api/current/html/index.html>

**Comment by esaule** [comment]
solved
